// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouecdvmcxbkvlxmjhzdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91ZWNkdm1jeGJrdmx4bWpoemRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTM4NjksImV4cCI6MjA2NjE2OTg2OX0.l3SEmPLkqRio6E9wyGtcyOTKenRpBTMzTENKQKEmD5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);